CREATE DATABASE db_NewOne;

USE db_NewOne;

CREATE TABLE bloque (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  origen VARCHAR(50) NOT NULL,
  cantidad VARCHAR(50) NOT NULL,
  destino VARCHAR(50) NOT NULL,
  prevhash VARCHAR(100),
  acthash VARCHAR(100)
);

